apiVersion: v1
kind: ReplicationController
metadata:
  name: ooo-email-detect-dev
spec:
  replicas: 2
  selector:
    app: ooo-email-detect-dev
  template:
    metadata:
      name: ooo-email-detect-dev
      labels:
        app: ooo-email-detect-dev
    spec:
      containers:
      - name: ooo-email-detect-dev
        imagePullPolicy: Always
        image: gcr.io/d1-labs/ooo-email-detect:latest
        ports:
        - containerPort: 8080
        env:
          - name: ENV
            value: dev